### ISSUE TITLE
Add xdebug

### ISSUE THREAD

**Issue by leepownall** [agjmills/laravel-docker-tutorial#1]
Hello there!

Could you add an example or add xdebug?

**Comment by agjmills** [comment]
I've added an example of xdebug usage here: https://github.com/agjmills/laravel-docker-tutorial/tree/xdebug

Could you give it a try and let me know if that works for you?

**Comment by leepownall** [comment]
Can't seem to get PHPStorm to detect that xdebug is installed.

<img width="610" alt="Screenshot 2020-08-04 at 16 33 28" src="https://user-images.githubusercontent.com/757140/89313435-648f1000-d670-11ea-8c24-0824b6944dbe.png">

I've done `docker-compose down` and `docker-compose up -d --force-recreate` but it never changes.
